In [97]:
import os
import numpy as np
import nibabel

data_path = 'data2021/'
# we will undersample our training 2D images later (for memory and speed)
img_rows = int(192)
img_cols = int(192)

%config Completer.use_jedi = False

## Loading paths

In [98]:
train_imgs_path = os.path.join(data_path, 'train/img_train')
train_masks_path = os.path.join(data_path, 'train/mask_train')

imgs_train = []
masks_train = []

# Lists for saving nonzero slices of training data
nonzero_imgs_train = []
nonzero_masks_train = []

imgs_testt = []

## Creating train data

In [99]:
for dirr in sorted(os.listdir(train_imgs_path)):
    dirr = os.path.join(train_imgs_path, dirr)
    print(dirr)

#         training_images += nifti_scan[::1]
        
    training_image = nibabel.load(dirr)
    for k in range(training_image.shape[2]):
        image_2d = np.array(training_image.get_fdata()[::, ::, k])

        imgs_train.append(image_2d)

print(len(imgs_train))
        
# imgs = np.ndarray((len(imgs_train), image_rows, image_cols), dtype=np.float32)

#         print(imgs.max())

data2021/train/img_train\01.nii
data2021/train/img_train\011.nii
data2021/train/img_train\012.nii
data2021/train/img_train\02.nii
data2021/train/img_train\021.nii
data2021/train/img_train\022.nii
data2021/train/img_train\03.nii
data2021/train/img_train\031.nii
data2021/train/img_train\032.nii
data2021/train/img_train\04.nii
data2021/train/img_train\041.nii
data2021/train/img_train\042.nii
data2021/train/img_train\05.nii
data2021/train/img_train\051.nii
data2021/train/img_train\052.nii
data2021/train/img_train\06.nii
data2021/train/img_train\061.nii
data2021/train/img_train\062.nii
data2021/train/img_train\07.nii
data2021/train/img_train\071.nii
data2021/train/img_train\072.nii
data2021/train/img_train\08.nii
data2021/train/img_train\081.nii
data2021/train/img_train\082.nii
data2021/train/img_train\09.nii
data2021/train/img_train\091.nii
data2021/train/img_train\092.nii
data2021/train/img_train\10.nii
data2021/train/img_train\101.nii
data2021/train/img_train\102.nii
data2021/train/img_t

In [100]:
print(imgs_train[0])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [101]:
for dirr in sorted(os.listdir(train_masks_path)):
    dirr = os.path.join(train_masks_path, dirr)
#     nifti_files = sorted(os.listdir(dirr))
    print(dirr)

    training_mask = nibabel.load(dirr)
    i = 0
    
#   Saving the mask 3 times in a row to match with 3 modalities
    for i in range(3):
        for k in range(training_mask.shape[2]):
            mask_2d = np.array(training_mask.get_fdata()[::, ::, k])
            masks_train.append(mask_2d)

len(masks_train)
        
# #         imgs = np.ndarray((len(imgs_train), image_rows, image_cols), dtype=np.float32)

data2021/train/mask_train\01.nii
data2021/train/mask_train\02.nii
data2021/train/mask_train\03.nii
data2021/train/mask_train\04.nii
data2021/train/mask_train\05.nii
data2021/train/mask_train\06.nii
data2021/train/mask_train\07.nii
data2021/train/mask_train\08.nii
data2021/train/mask_train\09.nii
data2021/train/mask_train\10.nii
data2021/train/mask_train\11.nii
data2021/train/mask_train\12.nii
data2021/train/mask_train\13.nii
data2021/train/mask_train\14.nii
data2021/train/mask_train\15.nii
data2021/train/mask_train\16.nii
data2021/train/mask_train\17.nii
data2021/train/mask_train\18.nii
data2021/train/mask_train\19.nii
data2021/train/mask_train\20.nii
data2021/train/mask_train\21.nii
data2021/train/mask_train\22.nii
data2021/train/mask_train\23.nii
data2021/train/mask_train\24.nii
data2021/train/mask_train\25.nii
data2021/train/mask_train\26.nii
data2021/train/mask_train\27.nii
data2021/train/mask_train\28.nii
data2021/train/mask_train\29.nii
data2021/train/mask_train\30.nii
data2021/t

23040

## Filtering out nonzero slices

In [103]:
for i in range(23040):
    for j in range(192):
        if any(masks_train[i][j]):
            nonzero_imgs_train.append(imgs_train[i])
            nonzero_masks_train.append(masks_train[i])
            break

In [105]:
print(len(imgs_train))
print(len(nonzero_imgs_train))

print(len(masks_train))
print(len(nonzero_masks_train))

23040
8109
23040
8109


## Converting nonzero lists to numpy

In [108]:
nonzero_imgs = np.asarray(nonzero_imgs_train)
nonzero_imgs_mask = np.asarray(nonzero_masks_train)

In [109]:
nonzero_imgs.shape, type(nonzero_imgs), nonzero_imgs_mask.shape, type(nonzero_imgs_mask)

((8109, 192, 192), numpy.ndarray, (8109, 192, 192), numpy.ndarray)

In [112]:
print(nonzero_imgs.max())
print(nonzero_imgs_mask.max())

2687229.25
1.0000000591389835


In [115]:
# for index, img in enumerate(nonzero_imgs):
#     nonzero_imgs_train[index, :, :] = img

# for index, img in enumerate(nonzero_imgs_mask):
#     nonzero_masks_train[index, :, :] = img

## Saving nonzero numpy arrays

In [116]:
np.save('nonzero_imgs_train2021mar.npy', nonzero_imgs)
np.save('nonzero_masks_train2021mar.npy', nonzero_imgs_mask)

## Converting lists with nonzero values to numpy

In [5]:
imgs = np.asarray(imgs_train)
imgs_mask = np.asarray(masks_train)

In [6]:
imgs.shape, type(imgs), imgs_mask.shape, type(imgs_mask)

((23040, 192, 192), numpy.ndarray, (23040, 192, 192), numpy.ndarray)

In [7]:
print(imgs.max())
print(imgs_mask.max())

4756936.5
1.0000000591389835


In [8]:
for index, img in enumerate(imgs_train):
    imgs[index, :, :] = img

for index, img in enumerate(masks_train):
    imgs_mask[index, :, :] = img

In [9]:
imgs.shape, type(imgs), imgs_mask.shape, type(imgs_mask)

((23040, 192, 192), numpy.ndarray, (23040, 192, 192), numpy.ndarray)

In [10]:
print(imgs.max())
print(imgs_mask.max())

4756936.5
1.0000000591389835


## Creating test data

In [12]:
imgs_testt = []
print(len(imgs_testt))

test_imgs_path = os.path.join(data_path, 'test')

for dirr in sorted(os.listdir(test_imgs_path)):
    dirr = os.path.join(test_imgs_path, dirr)
    print(dirr)

#         training_images += nifti_scan[::1]
        
    testing_image = nibabel.load(dirr)
    for k in range(testing_image.shape[2]):
        image_2d = np.array(testing_image.get_fdata()[::, ::, k])

        imgs_testt.append(image_2d)

print(len(imgs_testt))

0
data2021/test\01.nii
data2021/test\02.nii
data2021/test\03.nii
data2021/test\04.nii
data2021/test\05.nii
data2021/test\06.nii
data2021/test\07.nii
data2021/test\08.nii
data2021/test\09.nii
data2021/test\10.nii
data2021/test\11.nii
data2021/test\12.nii
data2021/test\13.nii
data2021/test\14.nii
data2021/test\15.nii
2880


In [13]:
imgs_test = np.asarray(imgs_testt)
imgs_test.shape, type(imgs_test)

((2880, 192, 192), numpy.ndarray)

In [14]:
print(imgs_test.max())

112689.859375


In [15]:
for index, img in enumerate(imgs_testt):
    imgs_test[index, :, :] = img

## Saving numpy arrays with nonzero values

In [16]:
np.save('imgs_train2021mar.npy', imgs)
np.save('masks_train2021mar.npy', imgs_mask)

np.save('imgs_test2021mar.npy', imgs_test)


In [5]:
hlavy = np.load('./imgs_train2021mar.npy')
masky = np.load('./masks_train2021mar.npy')

print(hlavy.max(), masky.max())

4756936.5 1.0000000591389835


# Predicting from trained weights

In [3]:
def dice_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)


def dice_coef_loss(y_true, y_pred):
    return 1-dice_coef(y_true, y_pred)

In [4]:
def get_unet():
    inputs = Input((img_rows, img_cols, 1))
    conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
    conv1 = Conv2D(32, (3, 3), activation='relu', padding='same')(conv1)
    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

    conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(pool1)
    conv2 = Conv2D(64, (3, 3), activation='relu', padding='same')(conv2)
    pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)

    conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(pool2)
    conv3 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv3)
    pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)

    conv4 = Conv2D(256, (3, 3), activation='relu', padding='same')(pool3)
    conv4 = Conv2D(256, (3, 3), activation='relu', padding='same')(conv4)
    pool4 = MaxPooling2D(pool_size=(2, 2))(conv4)

    conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(pool4)
    conv5 = Conv2D(512, (3, 3), activation='relu', padding='same')(conv5)

    up6 = concatenate([Conv2DTranspose(256, (2, 2), strides=(2, 2), padding='same')(conv5), conv4], axis=3)
    conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(up6)
    conv6 = Conv2D(256, (3, 3), activation='relu', padding='same')(conv6)

    up7 = concatenate([Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(conv6), conv3], axis=3)
    conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(up7)
    conv7 = Conv2D(128, (3, 3), activation='relu', padding='same')(conv7)

    up8 = concatenate([Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(conv7), conv2], axis=3)
    conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(up8)
    conv8 = Conv2D(64, (3, 3), activation='relu', padding='same')(conv8)

    up9 = concatenate([Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(conv8), conv1], axis=3)
    conv9 = Conv2D(32, (3, 3), activation='relu', padding='same')(up9)
    conv9 = Conv2D(32, (3, 3), activation='relu', padding='same')(conv9)

    conv10 = Conv2D(1, (1, 1), activation='sigmoid')(conv9)

    model = Model(inputs=[inputs], outputs=[conv10])

#     model.compile(optimizer=Adam(lr=1e-5), loss=dice_coef_loss, metrics=[dice_coef])
#     model.compile(optimizer=Adam(lr=1e-4), loss=dice_coef_loss, metrics=[dice_coef, 'accuracy'])

#     model.compile(optimizer=Adam(lr=1e-4), loss=Combo_loss, metrics=[dice_coef, 'accuracy'])
   
    model.compile(optimizer=Adam(lr=1e-4), loss='binary_crossentropy', metrics=[dice_coef, 'accuracy'])

    
    return model


def preprocess(imgs):
    imgs_p = np.ndarray((imgs.shape[0], img_rows, img_cols), dtype=np.float32)
    for i in range(imgs.shape[0]):
        imgs_p[i] = resize(imgs[i], (img_cols, img_rows), preserve_range=True)

    imgs_p = imgs_p[..., np.newaxis]
    return imgs_p

In [13]:
def load_test_data():
    imgs_test = np.load('imgs_test2021feb.npy')
    masks_test = np.load('imgs_test2021feb.npy')
    return imgs_test, masks_test

def predict():    
    
    print('-'*30)
    print('Loading and preprocessing test data...')
    print('-'*30)
    imgs_test, imgs_maskt = load_test_data()
    imgs_test = preprocess(imgs_test)

    imgs_test = imgs_test.astype('float32')
    # imgs_test -= mean
    # imgs_test /= std

    imgs_test /= imgs_test.max()
    imgs_test = imgs_test.astype('float32')

#     imgs_mask_test /= imgs_mask_test.max()
#     imgs_mask_test = imgs_mask_test.astype('float32')

    print('-'*30)
    print('Loading saved weights...')
    print('-'*30)
#     model = get_unet()
#     model.load_weights('weights2021feb.h5')

    print('-'*30)
    print('Predicting masks on test data...')
    print('-'*30)
#     imgs_mask_test = model.predict(imgs_test, verbose=1)
#     np.save('imgs_mask_testfeb2021.npy', imgs_mask_test)
    imgs_mask_test = np.load('imgs_mask_testfeb2021.npy')

    print('-' * 30)
    print('Saving predicted masks to files...')
    print('-' * 30)
    
    pred_dir = 'preds2'
    if not os.path.exists(pred_dir):
        os.mkdir(pred_dir)
#     for k in range(len(imgs_mask_test)):
#         image = (imgs_mask_test[:, :, 0] * 255.).astype(np.uint8)
#         imsave(os.path.join(pred_dir, str(k) + '_pred.png'), image)

    for k in range(len(imgs_mask_test)):
        a=rescale_intensity(imgs_test[k][:,:,0],out_range=(-1,1))
        b=(imgs_mask_test[k][:,:,0]).astype('uint8')
        io.imsave(os.path.join(pred_dir, str(k) + '_pred.png'),mark_boundaries(a,b)) 
#         io.imsave(os.path.join(pred_dir, str(k) + '_pred.png'),b) 
        

#     plt.plot(history.history['dice_coef'])
#     plt.plot(history.history['val_dice_coef'])
#     plt.title('Model dice coeff')
#     plt.ylabel('Dice coeff')
#     plt.xlabel('Epoch')
#     plt.legend(['Train', 'Test'], loc='upper left')
#     # plt.show()
#     plt.savefig('progr.png')
#     # plotting our dice coeff results in function of the number of epochs

## Predicting to save slices of images

In [14]:
import os
from skimage.transform import resize
from skimage.io import imsave
import numpy as np
from keras.models import Model
from keras.layers import Input, concatenate, Conv2D, MaxPooling2D, Conv2DTranspose
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint
from keras import backend as K
import matplotlib.pyplot as plt
from keras.callbacks import History
from skimage import io
from skimage.segmentation import mark_boundaries
from skimage.exposure import rescale_intensity


if __name__ == '__main__':
#     train()
    predict()

------------------------------
Loading and preprocessing test data...
------------------------------
------------------------------
Loading saved weights...
------------------------------
------------------------------
Predicting masks on test data...
------------------------------


/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/0_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/1_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/2_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/3_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 pr

------------------------------
Saving predicted masks to files...
------------------------------


/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/7_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/8_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/9_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
/home/dom/anaconda3/envs/thesis/lib/python3.6/site-packages/ipykernel_launcher.py:51: UserWarning: preds2/10_pred.png is a low contrast image
Lossy conversion from float64 to uint8. Range [0, 1]. Convert image to uint8 p